# Data Preparation

This notebook inspects the datasets under `maxtoki_development_data` and prints a small head/preview for each file.

The data directory is large, so the code below is intentionally conservative:

- `.h5ad` files are opened with `anndata.read_h5ad(..., backed="r")` when `anndata` is available.
- `.mtx.gz` files are previewed by reading the Matrix Market header and first coordinate rows rather than loading the full matrix.
- `.tsv.gz` files are previewed by streaming the first lines and first columns.
- `.loom` files are previewed with `h5py` by reading only a small matrix slice and attribute keys.
- Supporting `.txt` and `.pickle` files are inspected separately at the end.

In [1]:
from pathlib import Path
import gzip
import os
import pickle
import sys
from datetime import datetime

try:
    import pandas as pd
except Exception as exc:
    pd = None
    print(f"pandas unavailable: {exc}")

try:
    import numpy as np
except Exception as exc:
    np = None
    print(f"numpy unavailable: {exc}")

try:
    import anndata as ad
except Exception as exc:
    ad = None
    print(f"anndata unavailable: {exc}")

try:
    import h5py
except Exception as exc:
    h5py = None
    print(f"h5py unavailable: {exc}")

try:
    from IPython.display import display, Markdown
except Exception:
    display = print
    Markdown = lambda text: text

DATA_DIR = Path("/gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data")
HEAD_N = 5
MAX_COLUMNS = 8

print(f"Notebook run started: {datetime.now().isoformat(timespec='seconds')}")
print(f"Data directory: {DATA_DIR}")
print(f"Exists: {DATA_DIR.exists()}")

Notebook run started: 2026-04-15T16:11:14
Data directory: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data
Exists: True

## Dataset Manifest

This manifest is the current 21-file dataset scope: 10 CellxGene `.h5ad` files, 1 HCA Matrix Market file, 5 UCSC/local matrices, and 5 lab `.loom` files.

In [2]:
DATASETS = [
    {
        "source": "CellxGene",
        "name": "Construction of a human cell landscape at single-cell level",
        "path": DATA_DIR / "source_1_cellxgene/01_construction_of_a_human_cell_landscape_at_single_cell_level.h5ad",
        "origin": "https://datasets.cellxgene.cziscience.com/74c3403a-451c-4a62-84e0-d8a8e45c7ea7.h5ad",
    },
    {
        "source": "CellxGene",
        "name": "Survey of human embryonic development (1 million cells subset)",
        "path": DATA_DIR / "source_1_cellxgene/02_survey_of_human_embryonic_development_1_million_cells_subset.h5ad",
        "origin": "https://datasets.cellxgene.cziscience.com/c3bf819d-423d-435f-b8d0-e36ad6088138.h5ad",
    },
    {
        "source": "CellxGene",
        "name": "Survey of human embryonic development",
        "path": DATA_DIR / "source_1_cellxgene/03_survey_of_human_embryonic_development.h5ad",
        "origin": "https://datasets.cellxgene.cziscience.com/dd2564a6-27a0-433a-893c-72475e4a39fe.h5ad",
    },
    {
        "source": "CellxGene",
        "name": "Sex-Specific Control of Human Heart Maturation by the Progesterone Receptor",
        "path": DATA_DIR / "source_1_cellxgene/04_sex_specific_control_of_human_heart_maturation_by_the_progesterone_receptor.h5ad",
        "origin": "https://datasets.cellxgene.cziscience.com/d61a74ab-e1ef-4ced-9131-698bf7d94be2.h5ad",
    },
    {
        "source": "CellxGene",
        "name": "Integrated adult and foetal hearts",
        "path": DATA_DIR / "source_1_cellxgene/05_integrated_adult_and_foetal_hearts.h5ad",
        "origin": "https://datasets.cellxgene.cziscience.com/51073d23-97b7-4c05-84eb-5a18024e966c.h5ad",
    },
    {
        "source": "CellxGene",
        "name": "Rotem_12W_heart_C1",
        "path": DATA_DIR / "source_1_cellxgene/06_rotem_12w_heart_c1.h5ad",
        "origin": "https://datasets.cellxgene.cziscience.com/380b448b-85de-4953-8e82-2fda20276a12.h5ad",
    },
    {
        "source": "CellxGene",
        "name": "Rotem_12W_heart_B1",
        "path": DATA_DIR / "source_1_cellxgene/07_rotem_12w_heart_b1.h5ad",
        "origin": "https://datasets.cellxgene.cziscience.com/57c7e31e-6bf5-4498-a2d3-2a3728c64ded.h5ad",
    },
    {
        "source": "CellxGene",
        "name": "Rotem_12W_heart_D1",
        "path": DATA_DIR / "source_1_cellxgene/08_rotem_12w_heart_d1.h5ad",
        "origin": "https://datasets.cellxgene.cziscience.com/72e35ce5-fb20-46d0-adf9-a8c7f44af287.h5ad",
    },
    {
        "source": "CellxGene",
        "name": "Rotem_12W_heart_A1",
        "path": DATA_DIR / "source_1_cellxgene/09_rotem_12w_heart_a1.h5ad",
        "origin": "https://datasets.cellxgene.cziscience.com/731fb49f-4a81-48d5-9f28-ee1b08f1018d.h5ad",
    },
    {
        "source": "CellxGene",
        "name": "Single-nuclei RNA-seq of human outflow tract and aortic valve tissue",
        "path": DATA_DIR / "source_1_cellxgene/10_single_nuclei_rna_seq_human_outflow_tract_aortic_valve.h5ad",
        "origin": "https://datasets.cellxgene.cziscience.com/e6c07fbd-c90b-48c0-b6e3-b03b2d7218c5.h5ad",
    },
    {
        "source": "Human Early Embryogenesis Atlas",
        "name": "GSE157329 raw counts",
        "path": DATA_DIR / "source_2_human_early_embryogenesis_atlas/93a9e248-b704-419f-b5ab-a0b96eefeaa0/GSE157329_raw_counts.mtx.gz",
        "origin": "HCA/Azul manifest URL from documents/data_sources.txt",
    },
    {
        "source": "UCSC Cells",
        "name": "Human cardiogenesis in vitro expression matrix",
        "path": DATA_DIR / "source_3_ucsc_cells/01_human_cardiogenesis_in_vitro_exprMatrix.tsv.gz",
        "origin": "Local copy corresponding to https://cells.ucsc.edu/cardiogenesis-atac/in-vitro/exprMatrix.tsv.gz",
    },
    {
        "source": "UCSC Cells",
        "name": "Human cardiogenesis in vivo expression matrix",
        "path": DATA_DIR / "source_3_ucsc_cells/02_human_cardiogenesis_in_vivo_exprMatrix.tsv.gz",
        "origin": "Local copy corresponding to https://cells.ucsc.edu/cardiogenesis-atac/in-vivo/exprMatrix.tsv.gz",
    },
    {
        "source": "UCSC Cells",
        "name": "Multiomic human heart snRNA-seq matrix",
        "path": DATA_DIR / "source_3_ucsc_cells/03_multiomic_human_heart_snrna_seq_matrix.mtx.gz",
        "origin": "Local copy corresponding to https://cells.ucsc.edu/multiomic-human-heart/rna/matrix.mtx.gz",
    },
    {
        "source": "UCSC Cells",
        "name": "Multiomic human heart snATAC-seq matrix",
        "path": DATA_DIR / "source_3_ucsc_cells/04_multiomic_human_heart_snatac_seq_matrix.mtx.gz",
        "origin": "Local copy corresponding to https://cells.ucsc.edu/multiomic-human-heart/atac/matrix.mtx.gz",
    },
    {
        "source": "UCSC Cells",
        "name": "Heart of Cells overall heart scRNA-seq expression matrix",
        "path": DATA_DIR / "source_3_ucsc_cells/05_heart_of_cells_overall_heart_scrna_seq_exprMatrix.tsv.gz",
        "origin": "Local copy corresponding to UCSC Heart of Cells overall heart exprMatrix.tsv.gz",
    },
    {
        "source": "Lab Directory",
        "name": "Human fetal cis-regulatory elements",
        "path": DATA_DIR / "source_4_lab_directory/01_human_fetal_cis_regulatory_elements.loom",
        "origin": "/gladstone/theodoris/lab/genecorpus_XM/corpus_loom_files/genecorpus_95M_loom/9010519993/File_S3_Matrix.Gene_Raw_Counts_of_Cells.loom",
    },
    {
        "source": "Lab Directory",
        "name": "Human fetal striatum atlas",
        "path": DATA_DIR / "source_4_lab_directory/02_human_fetal_striatum_atlas.loom",
        "origin": "/gladstone/theodoris/lab/genecorpus_XM/corpus_loom_files/genecorpus_95M_loom/E-MTAB-8894/E-MTAB-8894.loom",
    },
    {
        "source": "Lab Directory",
        "name": "Human megakaryocyte development: yolk-sac stage",
        "path": DATA_DIR / "source_4_lab_directory/03_human_megakaryocyte_development/GSE144024_YS_Stage_gene.loom",
        "origin": "/gladstone/theodoris/lab/genecorpus_XM/corpus_loom_files/genecorpus_95M_loom/4110056855/",
    },
    {
        "source": "Lab Directory",
        "name": "Human megakaryocyte development: hESC Day 0",
        "path": DATA_DIR / "source_4_lab_directory/03_human_megakaryocyte_development/GSE144024_hESC_Day0_gene.loom",
        "origin": "/gladstone/theodoris/lab/genecorpus_XM/corpus_loom_files/genecorpus_95M_loom/4110056855/",
    },
    {
        "source": "Lab Directory",
        "name": "Fetal vs. adult human epicardium",
        "path": DATA_DIR / "source_4_lab_directory/04_fetal_vs_adult_human_epicardium.loom",
        "origin": "/gladstone/theodoris/lab/genecorpus_XM/corpus_loom_files/genecorpus_95M_loom/cxg/5500c673-1610-40a0-86d9-64d987ae50e6.loom",
    },
]

SUPPORTING_FILES = [
    DATA_DIR / "source_4_lab_directory/03_human_megakaryocyte_development/GSE144024_YS_Stage_gene_log.txt",
    DATA_DIR / "source_4_lab_directory/03_human_megakaryocyte_development/GSE144024_YS_Stage_gene_per_cell_summary.pickle",
    DATA_DIR / "source_4_lab_directory/03_human_megakaryocyte_development/GSE144024_YS_Stage_gene_postcheck.txt",
    DATA_DIR / "source_4_lab_directory/03_human_megakaryocyte_development/GSE144024_hESC_Day0_gene_log.txt",
    DATA_DIR / "source_4_lab_directory/03_human_megakaryocyte_development/GSE144024_hESC_Day0_gene_per_cell_summary.pickle",
    DATA_DIR / "source_4_lab_directory/03_human_megakaryocyte_development/GSE144024_hESC_Day0_gene_postcheck.txt",
]

In [3]:
def format_bytes(num_bytes):
    num_bytes = float(num_bytes)
    units = ["B", "KiB", "MiB", "GiB", "TiB"]
    value = num_bytes
    for unit in units:
        if value < 1024 or unit == units[-1]:
            if unit == "B":
                return f"{int(value)}{unit}"
            return f"{value:.1f}{unit}"
        value /= 1024


def file_size(path):
    path = Path(path)
    return path.stat().st_size if path.exists() else None


def show_table(rows, columns=None):
    if pd is not None:
        display(pd.DataFrame(rows, columns=columns))
    else:
        if columns:
            print("\t".join(map(str, columns)))
        for row in rows:
            print("\t".join(map(str, row)))


manifest_rows = []
for i, ds in enumerate(DATASETS, start=1):
    size = file_size(ds["path"])
    manifest_rows.append([
        i,
        ds["source"],
        ds["name"],
        format_bytes(size) if size is not None else "missing",
        str(ds["path"].relative_to(DATA_DIR)) if ds["path"].exists() else str(ds["path"]),
    ])

show_table(manifest_rows, columns=["#", "source", "dataset", "size", "relative_path"])

,#,source,dataset,size,relative_path
0,1,CellxGene,Construction of a human cell landscape at sing...,1.3GiB,source_1_cellxgene/01_construction_of_a_human_...
1,2,CellxGene,Survey of human embryonic development (1 milli...,4.6GiB,source_1_cellxgene/02_survey_of_human_embryoni...
2,3,CellxGene,Survey of human embryonic development,18.7GiB,source_1_cellxgene/03_survey_of_human_embryoni...
3,4,CellxGene,Sex-Specific Control of Human Heart Maturation...,816.5MiB,source_1_cellxgene/04_sex_specific_control_of_...
4,5,CellxGene,Integrated adult and foetal hearts,409.1MiB,source_1_cellxgene/05_integrated_adult_and_foe...
5,6,CellxGene,Rotem_12W_heart_C1,34.0MiB,source_1_cellxgene/06_rotem_12w_heart_c1.h5ad
6,7,CellxGene,Rotem_12W_heart_B1,36.7MiB,source_1_cellxgene/07_rotem_12w_heart_b1.h5ad
7,8,CellxGene,Rotem_12W_heart_D1,24.2MiB,source_1_cellxgene/08_rotem_12w_heart_d1.h5ad
8,9,CellxGene,Rotem_12W_heart_A1,42.8MiB,source_1_cellxgene/09_rotem_12w_heart_a1.h5ad
9,10,CellxGene,Single-nuclei RNA-seq of human outflow tract a...,437.1MiB,source_1_cellxgene/10_single_nuclei_rna_seq_hu...
10,11,Human Early Embryogenesis Atlas,GSE157329 raw counts,1.3GiB,source_2_human_early_embryogenesis_atlas/93a9e...
11,12,UCSC Cells,Human cardiogenesis in vitro expression matrix,1.7GiB,source_3_ucsc_cells/01_human_cardiogenesis_in_...
12,13,UCSC Cells,Human cardiogenesis in vivo expression matrix,340.3MiB,source_3_ucsc_cells/02_human_cardiogenesis_in_...
13,14,UCSC Cells,Multiomic human heart snRNA-seq matrix,20.5GiB,source_3_ucsc_cells/03_multiomic_human_heart_s...
14,15,UCSC Cells,Multiomic human heart snATAC-seq matrix,24.7GiB,source_3_ucsc_cells/04_multiomic_human_heart_s...
15,16,UCSC Cells,Heart of Cells overall heart scRNA-seq express...,360.6MiB,source_3_ucsc_cells/05_heart_of_cells_overall_...
16,17,Lab Directory,Human fetal cis-regulatory elements,1.2GiB,source_4_lab_directory/01_human_fetal_cis_regu...
17,18,Lab Directory,Human fetal striatum atlas,1.4GiB,source_4_lab_directory/02_human_fetal_striatum...
18,19,Lab Directory,Human megakaryocyte development: yolk-sac stage,90.9MiB,source_4_lab_directory/03_human_megakaryocyte_...
19,20,Lab Directory,Human megakaryocyte development: hESC Day 0,76.2MiB,source_4_lab_directory/03_human_megakaryocyte_...
20,21,Lab Directory,Fetal vs. adult human epicardium,302.0MiB,source_4_lab_directory/04_fetal_vs_adult_human...

## Preview Helpers

These functions print small heads/previews without materializing the full datasets.

In [4]:
def print_dataset_header(ds):
    path = Path(ds["path"])
    display(Markdown(f"### {ds['name']}"))
    print(f"Source: {ds['source']}")
    print(f"Path: {path}")
    print(f"Origin: {ds['origin']}")
    if not path.exists():
        print("MISSING")
        return False
    print(f"Size: {format_bytes(path.stat().st_size)}")
    return True


def preview_delimited_gz(path, n=HEAD_N, max_cols=MAX_COLUMNS, sep="\t"):
    rows = []
    with gzip.open(path, "rt", errors="replace") as handle:
        for idx, line in enumerate(handle):
            if idx >= n:
                break
            parts = line.rstrip("\n").split(sep)
            clipped = parts[:max_cols]
            if len(parts) > max_cols:
                clipped.append(f"... {len(parts) - max_cols} more columns")
            rows.append(clipped)
    show_table(rows)


def preview_mtx_gz(path, n=HEAD_N):
    header = None
    dims = None
    entries = []
    comments = []
    with gzip.open(path, "rt", errors="replace") as handle:
        header = handle.readline().strip()
        for line in handle:
            line = line.strip()
            if not line:
                continue
            if line.startswith("%"):
                if len(comments) < 3:
                    comments.append(line)
                continue
            dims = line
            break
        for line in handle:
            line = line.strip()
            if not line or line.startswith("%"):
                continue
            entries.append(line.split())
            if len(entries) >= n:
                break
    print(f"Matrix Market header: {header}")
    if comments:
        print("Comments:")
        for comment in comments:
            print(f"  {comment}")
    print(f"Matrix dimensions line: {dims}")
    columns = ["row", "column", "value"] if entries and len(entries[0]) >= 3 else None
    show_table(entries, columns=columns)


def preview_h5ad(path, n=HEAD_N):
    if ad is None:
        print("Install/load anndata in this kernel to inspect .h5ad files.")
        if h5py is not None:
            with h5py.File(path, "r") as handle:
                print(f"HDF5 top-level keys: {list(handle.keys())}")
        return

    adata = ad.read_h5ad(path, backed="r")
    try:
        print(adata)
        print(f"n_obs: {adata.n_obs:,}; n_vars: {adata.n_vars:,}")
        print("obs head:")
        display(adata.obs.head(n))
        print("var head:")
        display(adata.var.head(n))
        try:
            x = adata.X[:n, :n]
            if hasattr(x, "toarray"):
                x = x.toarray()
            if pd is not None:
                display(pd.DataFrame(x, index=adata.obs_names[:n], columns=adata.var_names[:n]))
            else:
                print(x)
        except Exception as exc:
            print(f"Could not preview X[:{n}, :{n}]: {exc}")
    finally:
        try:
            adata.file.close()
        except Exception:
            pass


def preview_loom(path, n=HEAD_N):
    if h5py is None:
        print("Install/load h5py or loompy in this kernel to inspect .loom files.")
        return

    with h5py.File(path, "r") as handle:
        print(f"HDF5 top-level keys: {list(handle.keys())}")
        matrix = handle.get("matrix")
        if matrix is None:
            print("No /matrix dataset found in loom file.")
            return
        print(f"matrix shape: {matrix.shape}; dtype: {matrix.dtype}")
        nr = min(n, matrix.shape[0])
        nc = min(n, matrix.shape[1])
        sample = matrix[:nr, :nc]
        if pd is not None:
            display(pd.DataFrame(sample))
        else:
            print(sample)
        row_attrs = list(handle.get("row_attrs", {}).keys()) if "row_attrs" in handle else []
        col_attrs = list(handle.get("col_attrs", {}).keys()) if "col_attrs" in handle else []
        print(f"row_attrs keys: {row_attrs[:20]}")
        print(f"col_attrs keys: {col_attrs[:20]}")


def preview_text(path, n=HEAD_N):
    with open(path, "rt", errors="replace") as handle:
        for idx, line in enumerate(handle):
            if idx >= n:
                break
            print(line.rstrip("\n")[:1000])


def preview_pickle(path):
    try:
        with open(path, "rb") as handle:
            obj = pickle.load(handle)
    except Exception as exc:
        print(f"Could not load pickle preview: {exc}")
        return
    print(f"pickle object type: {type(obj)}")
    if hasattr(obj, "head"):
        display(obj.head(HEAD_N))
    elif isinstance(obj, dict):
        keys = list(obj.keys())[:HEAD_N]
        print(f"first keys: {keys}")
        for key in keys:
            print(f"{key!r}: {repr(obj[key])[:500]}")
    else:
        print(repr(obj)[:1000])


def inspect_dataset(ds):
    if not print_dataset_header(ds):
        return
    path = Path(ds["path"])
    suffixes = "".join(path.suffixes).lower()
    if suffixes.endswith(".h5ad"):
        preview_h5ad(path)
    elif suffixes.endswith(".mtx.gz"):
        preview_mtx_gz(path)
    elif suffixes.endswith(".tsv.gz"):
        preview_delimited_gz(path)
    elif suffixes.endswith(".loom"):
        preview_loom(path)
    elif suffixes.endswith(".txt"):
        preview_text(path)
    elif suffixes.endswith(".pickle"):
        preview_pickle(path)
    else:
        print(f"No preview helper for suffixes: {suffixes}")

## Inspect All Main Datasets

Run the next cell to preview every main dataset. It may still take a few minutes because there are many large files, but it should not load the full 90G into memory.

In [10]:
for ds in DATASETS:
    inspect_dataset(ds)
    print("\n" + "-" * 100 + "\n")

### Construction of a human cell landscape at single-cell level

Source: CellxGene
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_1_cellxgene/01_construction_of_a_human_cell_landscape_at_single_cell_level.h5ad
Origin: https://datasets.cellxgene.cziscience.com/74c3403a-451c-4a62-84e0-d8a8e45c7ea7.h5ad
Size: 1.3GiB
AnnData object with n_obs × n_vars = 599926 × 26069 backed at '/gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_1_cellxgene/01_construction_of_a_human_cell_landscape_at_single_cell_level.h5ad'
    obs: 'batch', 'n_genes', 'n_counts', 'louvain', 'disease_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'tissue_original', 'assay_ontology_term_id', 'tissue_ontology_term_id', 'author_cell_type', 'cell_type_ontology_term_id', 'development_stage_ontology_term_id', 'sex_ontology_term_id', 'is_primary_data', 'donor_id', 'suspension_type', 'tissue_type', 'cell_type', 'assay', 'disease', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid'
    var: 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type'
    uns: 'citation', 'organism', 'organism_ontology_term_id', 'rank_genes_groups', 'schema_reference', 'schema_version', 'title'
    obsm: 'X_tsne', 'X_umap'
n_obs: 599,926; n_vars: 26,069
obs head:

,batch,n_genes,n_counts,louvain,disease_ontology_term_id,self_reported_ethnicity_ontology_term_id,tissue_original,assay_ontology_term_id,tissue_ontology_term_id,author_cell_type,...,suspension_type,tissue_type,cell_type,assay,disease,sex,tissue,self_reported_ethnicity,development_stage,observation_joinid
index,,,,,,,,,,,,,,,,,,,,,
AdultAdipose_1.TATGTAACACCCGCAGGA-0,AdultAdipose_1,911,1285.0,2,PATO:0000461,HANCESTRO:0027,AdultAdipose,EFO:0030002,UBERON:0001013,Macrophage,...,cell,tissue,macrophage,microwell-seq,normal,male,adipose tissue,Han Chinese,36-year-old stage,P!O5w%5Yll
AdultAdipose_1.CTCGCAAATAAACATCCC-0,AdultAdipose_1,1075,1628.0,2,PATO:0000461,HANCESTRO:0027,AdultAdipose,EFO:0030002,UBERON:0001013,Macrophage,...,cell,tissue,macrophage,microwell-seq,normal,male,adipose tissue,Han Chinese,36-year-old stage,A7^kr&W!s$
AdultAdipose_1.CGAGTATCGTAATACTTC-0,AdultAdipose_1,730,1018.0,2,PATO:0000461,HANCESTRO:0027,AdultAdipose,EFO:0030002,UBERON:0001013,Macrophage,...,cell,tissue,macrophage,microwell-seq,normal,male,adipose tissue,Han Chinese,36-year-old stage,vgUBNp?*1%
AdultAdipose_1.CTCGCAGCGAATCGGCAG-0,AdultAdipose_1,802,1145.0,2,PATO:0000461,HANCESTRO:0027,AdultAdipose,EFO:0030002,UBERON:0001013,Macrophage,...,cell,tissue,macrophage,microwell-seq,normal,male,adipose tissue,Han Chinese,36-year-old stage,jeH|zunzv0
AdultAdipose_1.ACGTTGATCAACAGATGG-0,AdultAdipose_1,622,852.0,2,PATO:0000461,HANCESTRO:0027,AdultAdipose,EFO:0030002,UBERON:0001013,Macrophage,...,cell,tissue,macrophage,microwell-seq,normal,male,adipose tissue,Han Chinese,36-year-old stage,Vts1QZY%G(

var head:

,feature_is_filtered,feature_name,feature_reference,feature_biotype,feature_length,feature_type
ENSG00000185189,False,NRBP2,NCBITaxon:9606,gene,2164,protein_coding
ENSG00000124191,False,TOX2,NCBITaxon:9606,gene,2376,protein_coding
ENSG00000116791,False,CRYZ,NCBITaxon:9606,gene,1592,protein_coding
ENSG00000271993,False,ENSG00000271993,NCBITaxon:9606,gene,628,lncRNA
ENSG00000273110,False,ENSG00000273110,NCBITaxon:9606,gene,681,lncRNA

,ENSG00000185189,ENSG00000124191,ENSG00000116791,ENSG00000271993,ENSG00000273110
index,,,,,
AdultAdipose_1.TATGTAACACCCGCAGGA-0,0.000000,0.0,0.0,0.0,0.0
AdultAdipose_1.CTCGCAAATAAACATCCC-0,1.966064,0.0,0.0,0.0,0.0
AdultAdipose_1.CGAGTATCGTAATACTTC-0,0.000000,0.0,0.0,0.0,0.0
AdultAdipose_1.CTCGCAGCGAATCGGCAG-0,0.000000,0.0,0.0,0.0,0.0
AdultAdipose_1.ACGTTGATCAACAGATGG-0,0.000000,0.0,0.0,0.0,0.0

----------------------------------------------------------------------------------------------------

### Survey of human embryonic development (1 million cells subset)

Source: CellxGene
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_1_cellxgene/02_survey_of_human_embryonic_development_1_million_cells_subset.h5ad
Origin: https://datasets.cellxgene.cziscience.com/c3bf819d-423d-435f-b8d0-e36ad6088138.h5ad
Size: 4.6GiB
AnnData object with n_obs × n_vars = 1001288 × 45676 backed at '/gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_1_cellxgene/02_survey_of_human_embryonic_development_1_million_cells_subset.h5ad'
    obs: 'All_reads', 'Batch', 'Development_day', 'Exon_reads', 'Experiment_batch', 'donor_id', 'Intron_reads', 'Main_cluster_name', 'Organ_cell_lineage', 'RT_group', 'batch', 'n_counts', 'sample', 'BCA_beta', 'BCA_cluster_info', 'MCA_beta', 'Matched_BCA_cell_name', 'Matched_MCA_cell_name', 'sub_cluster_id', 'sub_cluster_name', 'assay_ontology_term_id', 'disease_ontology_term_id', 'tissue_ontology_term_id', 'development_stage_ontology_term_id', 'cell_type_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'suspension_type', 'sex_ontology_term_id', 'is_primary_data', 'tissue_type', 'cell_type', 'assay', 'disease', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid'
    var: 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type'
    uns: 'cell_type_ontology_term_id_colors', 'citation', 'organism', 'organism_ontology_term_id', 'schema_reference', 'schema_version', 'title'
    obsm: 'X_global_umap', 'X_main_cluster_umap'
n_obs: 1,001,288; n_vars: 45,676
obs head:

,All_reads,Batch,Development_day,Exon_reads,Experiment_batch,donor_id,Intron_reads,Main_cluster_name,Organ_cell_lineage,RT_group,...,is_primary_data,tissue_type,cell_type,assay,disease,sex,tissue,self_reported_ethnicity,development_stage,observation_joinid
expr2-human-577well.TCGAGAAGTTAGGCAGATA,543,10,117,76,exp2,H27552,360,Retinal progenitors and Muller glia,Eye-Retinal progenitors and Muller glia,Eye_H27552,...,False,tissue,Mueller cell,sci-RNA-seq3,normal,male,eye,unknown,16th week post-fertilization stage,9nYBYuUK+H
expr2-human-577well.AGAGCATGTAACGGACCAA,338,10,117,56,exp2,H27552,231,Photoreceptor cells,Eye-Photoreceptor cells,Eye_H27552,...,False,tissue,photoreceptor cell,sci-RNA-seq3,normal,male,eye,unknown,16th week post-fertilization stage,KYn?5+W>9V
expr2-human-577well.TTCCATCTTTACTTAACTAG,723,10,117,109,exp2,H27552,495,Retinal progenitors and Muller glia,Eye-Retinal progenitors and Muller glia,Eye_H27552,...,False,tissue,Mueller cell,sci-RNA-seq3,normal,male,eye,unknown,16th week post-fertilization stage,?8@spd$vBM
expr2-human-577well.TGAGTTAGATCTGGATTAGT,334,10,117,58,exp2,H27552,200,Photoreceptor cells,Eye-Photoreceptor cells,Eye_H27552,...,False,tissue,photoreceptor cell,sci-RNA-seq3,normal,male,eye,unknown,16th week post-fertilization stage,=O_<p%2p>I
expr2-human-578well.TGCAAGGTTACTTAACTAG,360,10,117,74,exp2,H27552,236,Amacrine cells,Eye-Amacrine cells,Eye_H27552,...,False,tissue,amacrine cell,sci-RNA-seq3,normal,male,eye,unknown,16th week post-fertilization stage,L7GbtuB-j-

var head:

,feature_is_filtered,feature_name,feature_reference,feature_biotype,feature_length,feature_type
ENSG00000242915,False,SNRPGP7,NCBITaxon:9606,gene,106,processed_pseudogene
ENSG00000204661,False,SPATA31J1,NCBITaxon:9606,gene,1159,protein_coding
ENSG00000213137,False,ARF1P2,NCBITaxon:9606,gene,538,processed_pseudogene
ENSG00000261719,False,ENSG00000261719,NCBITaxon:9606,gene,223,processed_pseudogene
ENSG00000174327,False,SLC16A13,NCBITaxon:9606,gene,1386,protein_coding

,ENSG00000242915,ENSG00000204661,ENSG00000213137,ENSG00000261719,ENSG00000174327
expr2-human-577well.TCGAGAAGTTAGGCAGATA,0.0,0.0,0.0,0.0,0.0
expr2-human-577well.AGAGCATGTAACGGACCAA,0.0,0.0,0.0,0.0,0.0
expr2-human-577well.TTCCATCTTTACTTAACTAG,0.0,0.0,0.0,0.0,0.0
expr2-human-577well.TGAGTTAGATCTGGATTAGT,0.0,0.0,0.0,0.0,0.0
expr2-human-578well.TGCAAGGTTACTTAACTAG,0.0,0.0,0.0,0.0,0.0

----------------------------------------------------------------------------------------------------

### Survey of human embryonic development

Source: CellxGene
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_1_cellxgene/03_survey_of_human_embryonic_development.h5ad
Origin: https://datasets.cellxgene.cziscience.com/dd2564a6-27a0-433a-893c-72475e4a39fe.h5ad
Size: 18.7GiB
AnnData object with n_obs × n_vars = 4062980 × 45676 backed at '/gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_1_cellxgene/03_survey_of_human_embryonic_development.h5ad'
    obs: 'All_reads', 'Batch', 'Development_day', 'Exon_reads', 'Experiment_batch', 'donor_id', 'Intron_reads', 'Main_cluster_name', 'Organ_cell_lineage', 'RT_group', 'batch', 'n_counts', 'sample', 'BCA_beta', 'BCA_cluster_info', 'MCA_beta', 'Matched_BCA_cell_name', 'Matched_MCA_cell_name', 'sub_cluster_id', 'sub_cluster_name', 'assay_ontology_term_id', 'disease_ontology_term_id', 'tissue_ontology_term_id', 'development_stage_ontology_term_id', 'cell_type_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'suspension_type', 'sex_ontology_term_id', 'is_primary_data', 'tissue_type', 'cell_type', 'assay', 'disease', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid'
    var: 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type'
    uns: 'cell_type_ontology_term_id_colors', 'citation', 'organism', 'organism_ontology_term_id', 'schema_reference', 'schema_version', 'title'
    obsm: 'X_global_umap', 'X_main_cluster_umap'
n_obs: 4,062,980; n_vars: 45,676
obs head:

,All_reads,Batch,Development_day,Exon_reads,Experiment_batch,donor_id,Intron_reads,Main_cluster_name,Organ_cell_lineage,RT_group,...,is_primary_data,tissue_type,cell_type,assay,disease,sex,tissue,self_reported_ethnicity,development_stage,observation_joinid
expr2-human-577well.AAGGACGATTTCTTATCGA,372,10,117,70,exp2,H27552,243,Retinal progenitors and Muller glia,Eye-Retinal progenitors and Muller glia,Eye_H27552,...,True,tissue,Mueller cell,sci-RNA-seq3,normal,male,eye,unknown,16th week post-fertilization stage,uQRIw#CShz
expr2-human-577well.AACTAGTTGTGGTCCAGGAG,458,10,117,84,exp2,H27552,299,Amacrine cells,Eye-Amacrine cells,Eye_H27552,...,True,tissue,amacrine cell,sci-RNA-seq3,normal,male,eye,unknown,16th week post-fertilization stage,x3QZdSbks&
expr2-human-577well.GCAACGTTTCTGATTAAGA,1005,10,117,137,exp2,H27552,700,Amacrine cells,Eye-Amacrine cells,Eye_H27552,...,True,tissue,amacrine cell,sci-RNA-seq3,normal,male,eye,unknown,16th week post-fertilization stage,3XN!LJSDr;
expr2-human-577well.AAACCATAGTCCATTATCTA,469,4,129,82,exp2,H27458,324,Retinal progenitors and Muller glia,Eye-Retinal progenitors and Muller glia,Eye_H27458,...,True,tissue,Mueller cell,sci-RNA-seq3,normal,female,eye,unknown,18th week post-fertilization stage,7ea6jPAj}>
expr2-human-577well.TCGAGAAGTTAGGCAGATA,543,10,117,76,exp2,H27552,360,Retinal progenitors and Muller glia,Eye-Retinal progenitors and Muller glia,Eye_H27552,...,True,tissue,Mueller cell,sci-RNA-seq3,normal,male,eye,unknown,16th week post-fertilization stage,9nYBYuUK+H

var head:

,feature_is_filtered,feature_name,feature_reference,feature_biotype,feature_length,feature_type
ENSG00000242915,False,SNRPGP7,NCBITaxon:9606,gene,106,processed_pseudogene
ENSG00000204661,False,SPATA31J1,NCBITaxon:9606,gene,1159,protein_coding
ENSG00000213137,False,ARF1P2,NCBITaxon:9606,gene,538,processed_pseudogene
ENSG00000261719,False,ENSG00000261719,NCBITaxon:9606,gene,223,processed_pseudogene
ENSG00000174327,False,SLC16A13,NCBITaxon:9606,gene,1386,protein_coding

,ENSG00000242915,ENSG00000204661,ENSG00000213137,ENSG00000261719,ENSG00000174327
expr2-human-577well.AAGGACGATTTCTTATCGA,0.0,0.0,0.0,0.0,0.0
expr2-human-577well.AACTAGTTGTGGTCCAGGAG,0.0,0.0,0.0,0.0,0.0
expr2-human-577well.GCAACGTTTCTGATTAAGA,0.0,0.0,0.0,0.0,0.0
expr2-human-577well.AAACCATAGTCCATTATCTA,0.0,0.0,0.0,0.0,0.0
expr2-human-577well.TCGAGAAGTTAGGCAGATA,0.0,0.0,0.0,0.0,0.0

----------------------------------------------------------------------------------------------------

### Sex-Specific Control of Human Heart Maturation by the Progesterone Receptor

Source: CellxGene
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_1_cellxgene/04_sex_specific_control_of_human_heart_maturation_by_the_progesterone_receptor.h5ad
Origin: https://datasets.cellxgene.cziscience.com/d61a74ab-e1ef-4ced-9131-698bf7d94be2.h5ad
Size: 816.5MiB
AnnData object with n_obs × n_vars = 51176 × 35477 backed at '/gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_1_cellxgene/04_sex_specific_control_of_human_heart_maturation_by_the_progesterone_receptor.h5ad'
    obs: 'sample_id', 'donor_id', 'protocol_url', 'institute', 'library_id', 'library_id_repository', 'manner_of_death', 'sample_source', 'sex_ontology_term_id', 'sample_collection_method', 'tissue_type', 'sampled_site_condition', 'tissue_ontology_term_id', 'tissue_free_text', 'sample_preservation_method', 'suspension_type', 'cell_enrichment', 'sample_collection_year', 'assay_ontology_term_id', 'library_preparation_batch', 'library_sequencing_run', 'sequenced_fragment', 'sequencing_platform', 'is_primary_data', 'reference_genome', 'gene_annotation_version', 'alignment_software', 'intron_inclusion', 'disease_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'development_stage_ontology_term_id', 'cell_type_ontology_term_id', 'cell_type', 'assay', 'disease', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid'
    var: 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type'
    uns: 'batch_condition', 'citation', 'default_embedding', 'organism', 'organism_ontology_term_id', 'schema_reference', 'schema_version', 'study_pi', 'title'
    obsm: 'X_umap'
n_obs: 51,176; n_vars: 35,477
obs head:

,sample_id,donor_id,protocol_url,institute,library_id,library_id_repository,manner_of_death,sample_source,sex_ontology_term_id,sample_collection_method,...,development_stage_ontology_term_id,cell_type_ontology_term_id,cell_type,assay,disease,sex,tissue,self_reported_ethnicity,development_stage,observation_joinid
TACATTCTCTTACCAT_f1,fetal_1,SAMN15889156,PMID:33682422,Murdoch Children's Research Institute,fetal_healthy_1,GSM4742857,unknown,postmortem donor,PATO:0000384,biopsy,...,HsapDv:0000056,CL:0000746,cardiac muscle cell,10x 3' v3,normal,male,apical region of left ventricle,unknown,19th week post-fertilization stage,Wr1*XqNztZ
TATGTTCTCACTAGCA_f1,fetal_1,SAMN15889156,PMID:33682422,Murdoch Children's Research Institute,fetal_healthy_1,GSM4742857,unknown,postmortem donor,PATO:0000384,biopsy,...,HsapDv:0000056,CL:0000746,cardiac muscle cell,10x 3' v3,normal,male,apical region of left ventricle,unknown,19th week post-fertilization stage,0wr^qtOy)N
TCTAACTAGTAATACG_f1,fetal_1,SAMN15889156,PMID:33682422,Murdoch Children's Research Institute,fetal_healthy_1,GSM4742857,unknown,postmortem donor,PATO:0000384,biopsy,...,HsapDv:0000056,CL:0000746,cardiac muscle cell,10x 3' v3,normal,male,apical region of left ventricle,unknown,19th week post-fertilization stage,?LFU7Y19#H
AGTACTGCACCCTTGT_f1,fetal_1,SAMN15889156,PMID:33682422,Murdoch Children's Research Institute,fetal_healthy_1,GSM4742857,unknown,postmortem donor,PATO:0000384,biopsy,...,HsapDv:0000056,CL:0000738,leukocyte,10x 3' v3,normal,male,apical region of left ventricle,unknown,19th week post-fertilization stage,sPq#1BC~E}
ACTTCCGTCCTGTTAT_f1,fetal_1,SAMN15889156,PMID:33682422,Murdoch Children's Research Institute,fetal_healthy_1,GSM4742857,unknown,postmortem donor,PATO:0000384,biopsy,...,HsapDv:0000056,CL:0000746,cardiac muscle cell,10x 3' v3,normal,male,apical region of left ventricle,unknown,19th week post-fertilization stage,sAfaU#Mo~)

var head:

,feature_is_filtered,feature_name,feature_reference,feature_biotype,feature_length,feature_type
ENSG00000239945,False,ENSG00000239945,NCBITaxon:9606,gene,1319,lncRNA
ENSG00000241860,False,ENSG00000241860,NCBITaxon:9606,gene,861,lncRNA
ENSG00000286448,False,ENSG00000286448,NCBITaxon:9606,gene,728,lncRNA
ENSG00000229905,False,ENSG00000229905,NCBITaxon:9606,gene,456,lncRNA
ENSG00000237491,False,LINC01409,NCBITaxon:9606,gene,1089,lncRNA

,ENSG00000239945,ENSG00000241860,ENSG00000286448,ENSG00000229905,ENSG00000237491
TACATTCTCTTACCAT_f1,0.0,0.0,0.0,0.0,0.000000
TATGTTCTCACTAGCA_f1,0.0,0.0,0.0,0.0,0.169174
TCTAACTAGTAATACG_f1,0.0,0.0,0.0,0.0,0.189822
AGTACTGCACCCTTGT_f1,0.0,0.0,0.0,0.0,0.487801
ACTTCCGTCCTGTTAT_f1,0.0,0.0,0.0,0.0,0.000000

----------------------------------------------------------------------------------------------------

### Integrated adult and foetal hearts

Source: CellxGene
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_1_cellxgene/05_integrated_adult_and_foetal_hearts.h5ad
Origin: https://datasets.cellxgene.cziscience.com/51073d23-97b7-4c05-84eb-5a18024e966c.h5ad
Size: 409.1MiB
AnnData object with n_obs × n_vars = 60668 × 26886 backed at '/gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_1_cellxgene/05_integrated_adult_and_foetal_hearts.h5ad'
    obs: 'nCount_RNA', 'nFeature_RNA', 'age_group', 'cell_source', 'cell_states', 'sample', 'age.order', 'age.days.GA', 'size.CRL', 'size.NRL', 'stage', 'integration.groups', 'integrated_snn_res.0.1', 'clusters.low.res', 'clusters.high.res', 'clusters.res.2', 'clusters.res.3', 'condition', 'tissue_ontology_term_id', 'assay_ontology_term_id', 'disease_ontology_term_id', 'cell_type_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'development_stage_ontology_term_id', 'sex_ontology_term_id', 'donor_id', 'suspension_type', 'is_primary_data', 'tissue_type', 'cell_type', 'assay', 'disease', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid'
    var: 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type'
    uns: 'citation', 'organism', 'organism_ontology_term_id', 'schema_reference', 'schema_version', 'title'
    obsm: 'X_umap'
n_obs: 60,668; n_vars: 26,886
obs head:

,nCount_RNA,nFeature_RNA,age_group,cell_source,cell_states,sample,age.order,age.days.GA,size.CRL,size.NRL,...,is_primary_data,tissue_type,cell_type,assay,disease,sex,tissue,self_reported_ethnicity,development_stage,observation_joinid
GCGCGATCATACGCCG-alexsc,7071.0,2321,NA,F - Apex,foetal,alexsc,F5,67.0,NaN,NaN,...,True,tissue,fibroblast,10x 3' v2,normal,female,apex of heart,unknown,embryonic stage,NKCYKgS=h^
GCATGTAAGTATTGGA-alexsc,4345.0,1601,NA,F - Apex,foetal,alexsc,F5,67.0,NaN,NaN,...,True,tissue,fibroblast,10x 3' v2,normal,female,apex of heart,unknown,embryonic stage,Tc-7&J*Gbo
GACTGCGAGCTGAACG-alexsc,4533.0,1608,NA,F - Apex,foetal,alexsc,F5,67.0,NaN,NaN,...,True,tissue,fibroblast,10x 3' v2,normal,female,apex of heart,unknown,embryonic stage,_}j*xZ=USa
CCTTTCTTCTATCGCC-alexsc,7752.0,2341,NA,F - Apex,foetal,alexsc,F5,67.0,NaN,NaN,...,True,tissue,fibroblast,10x 3' v2,normal,female,apex of heart,unknown,embryonic stage,c72z};4{d<
CCAATCCAGCCACGCT-alexsc,10831.0,3109,NA,F - Apex,foetal,alexsc,F5,67.0,NaN,NaN,...,True,tissue,fibroblast,10x 3' v2,normal,female,apex of heart,unknown,embryonic stage,&OS^Sj5*tY

var head:

,feature_is_filtered,feature_name,feature_reference,feature_biotype,feature_length,feature_type
ENSG00000239945,False,ENSG00000239945,NCBITaxon:9606,gene,1319,lncRNA
ENSG00000237491,False,LINC01409,NCBITaxon:9606,gene,1089,lncRNA
ENSG00000177757,False,FAM87B,NCBITaxon:9606,gene,1960,lncRNA
ENSG00000225880,False,LINC00115,NCBITaxon:9606,gene,874,lncRNA
ENSG00000230368,False,FAM41C,NCBITaxon:9606,gene,919,lncRNA

,ENSG00000239945,ENSG00000237491,ENSG00000177757,ENSG00000225880,ENSG00000230368
GCGCGATCATACGCCG-alexsc,0.0,0.0,0.0,0.0,0.0
GCATGTAAGTATTGGA-alexsc,0.0,0.0,0.0,0.0,0.0
GACTGCGAGCTGAACG-alexsc,0.0,0.0,0.0,0.0,0.0
CCTTTCTTCTATCGCC-alexsc,0.0,0.0,0.0,0.0,0.0
CCAATCCAGCCACGCT-alexsc,0.0,0.0,0.0,0.0,0.0

----------------------------------------------------------------------------------------------------

### Rotem_12W_heart_C1

Source: CellxGene
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_1_cellxgene/06_rotem_12w_heart_c1.h5ad
Origin: https://datasets.cellxgene.cziscience.com/380b448b-85de-4953-8e82-2fda20276a12.h5ad
Size: 34.0MiB
AnnData object with n_obs × n_vars = 4992 × 35476 backed at '/gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_1_cellxgene/06_rotem_12w_heart_c1.h5ad'
    obs: 'in_tissue', 'array_row', 'array_col', 'suspension_type', 'assay_ontology_term_id', 'is_primary_data', 'donor_id', 'sex_ontology_term_id', 'development_stage_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'disease_ontology_term_id', 'tissue_type', 'tissue_ontology_term_id', 'q05cell_abundance_w_sf_Cardiac_x', 'q05cell_abundance_w_sf_Endothelial_x', 'q05cell_abundance_w_sf_Immune_x', 'q05cell_abundance_w_sf_Mesenchymal_clust12_x', 'q05cell_abundance_w_sf_Mesenchymal_clust15_x', 'q05cell_abundance_w_sf_Mesenchymal_clust3_x', 'q05cell_abundance_w_sf_Mesenchymal_clust6_x', 'q05cell_abundance_w_sf_Mesenchymal_clust9_x', 'q05cell_abundance_w_sf_Neural_x', 'annotation', 'cell_type_ontology_term_id', 'meanscell_abundance_w_sf_Cardiac', 'meanscell_abundance_w_sf_Endothelial', 'meanscell_abundance_w_sf_Immune', 'meanscell_abundance_w_sf_Mesenchymal_clust12', 'meanscell_abundance_w_sf_Mesenchymal_clust15', 'meanscell_abundance_w_sf_Mesenchymal_clust3', 'meanscell_abundance_w_sf_Mesenchymal_clust6', 'meanscell_abundance_w_sf_Mesenchymal_clust9', 'meanscell_abundance_w_sf_Neural', 'q05cell_abundance_w_sf_Cardiac_y', 'q05cell_abundance_w_sf_Endothelial_y', 'q05cell_abundance_w_sf_Immune_y', 'q05cell_abundance_w_sf_Mesenchymal_clust12_y', 'q05cell_abundance_w_sf_Mesenchymal_clust15_y', 'q05cell_abundance_w_sf_Mesenchymal_clust3_y', 'q05cell_abundance_w_sf_Mesenchymal_clust6_y', 'q05cell_abundance_w_sf_Mesenchymal_clust9_y', 'q05cell_abundance_w_sf_Neural_y', 'q95cell_abundance_w_sf_Cardiac', 'q95cell_abundance_w_sf_Endothelial', 'q95cell_abundance_w_sf_Immune', 'q95cell_abundance_w_sf_Mesenchymal_clust12', 'q95cell_abundance_w_sf_Mesenchymal_clust15', 'q95cell_abundance_w_sf_Mesenchymal_clust3', 'q95cell_abundance_w_sf_Mesenchymal_clust6', 'q95cell_abundance_w_sf_Mesenchymal_clust9', 'q95cell_abundance_w_sf_Neural', 'stdscell_abundance_w_sf_Cardiac', 'stdscell_abundance_w_sf_Endothelial', 'stdscell_abundance_w_sf_Immune', 'stdscell_abundance_w_sf_Mesenchymal_clust12', 'stdscell_abundance_w_sf_Mesenchymal_clust15', 'stdscell_abundance_w_sf_Mesenchymal_clust3', 'stdscell_abundance_w_sf_Mesenchymal_clust6', 'stdscell_abundance_w_sf_Mesenchymal_clust9', 'stdscell_abundance_w_sf_Neural', 'cell_type', 'assay', 'disease', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid'
    var: 'feature_types', 'genome', 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type'
    uns: 'citation', 'organism', 'organism_ontology_term_id', 'schema_reference', 'schema_version', 'spatial', 'spatial_metadata', 'title'
    obsm: 'MT', 'spatial'
n_obs: 4,992; n_vars: 35,476
obs head:

,in_tissue,array_row,array_col,suspension_type,assay_ontology_term_id,is_primary_data,donor_id,sex_ontology_term_id,development_stage_ontology_term_id,self_reported_ethnicity_ontology_term_id,...,stdscell_abundance_w_sf_Mesenchymal_clust9,stdscell_abundance_w_sf_Neural,cell_type,assay,disease,sex,tissue,self_reported_ethnicity,development_stage,observation_joinid
AAACAACGAATAGTTC-1,0,0,16,na,EFO:0022857,True,HsapDv:0000050,PATO:0000383,HsapDv:0000050,unknown,...,NaN,NaN,unknown,Visium Spatial Gene Expression V1,normal,female,outflow tract myocardium,unknown,13th week post-fertilization stage,S{qkR!yc~8
AAACAAGTATCTCCCA-1,1,50,102,na,EFO:0022857,True,HsapDv:0000050,PATO:0000383,HsapDv:0000050,unknown,...,0.210420,0.132565,cardiac mesenchymal cell,Visium Spatial Gene Expression V1,normal,female,outflow tract myocardium,unknown,13th week post-fertilization stage,gFD!+Zqd(i
AAACAATCTACTAGCA-1,0,3,43,na,EFO:0022857,True,HsapDv:0000050,PATO:0000383,HsapDv:0000050,unknown,...,NaN,NaN,unknown,Visium Spatial Gene Expression V1,normal,female,outflow tract myocardium,unknown,13th week post-fertilization stage,OsSlEREYZW
AAACACCAATAACTGC-1,0,59,19,na,EFO:0022857,True,HsapDv:0000050,PATO:0000383,HsapDv:0000050,unknown,...,NaN,NaN,unknown,Visium Spatial Gene Expression V1,normal,female,outflow tract myocardium,unknown,13th week post-fertilization stage,zuU(#yRj2=
AAACAGAGCGACTCCT-1,1,14,94,na,EFO:0022857,True,HsapDv:0000050,PATO:0000383,HsapDv:0000050,unknown,...,0.152805,0.142886,cardiac muscle cell,Visium Spatial Gene Expression V1,normal,female,outflow tract myocardium,unknown,13th week post-fertilization stage,-$<USDZJGm

var head:

,feature_types,genome,feature_is_filtered,feature_name,feature_reference,feature_biotype,feature_length,feature_type
gene_ids,,,,,,,,
ENSG00000243485,Gene Expression,GRCh38,False,MIR1302-2HG,NCBITaxon:9606,gene,517,lncRNA
ENSG00000237613,Gene Expression,GRCh38,False,FAM138A,NCBITaxon:9606,gene,1015,lncRNA
ENSG00000186092,Gene Expression,GRCh38,False,OR4F5,NCBITaxon:9606,gene,2618,protein_coding
ENSG00000239945,Gene Expression,GRCh38,False,ENSG00000239945,NCBITaxon:9606,gene,1319,lncRNA
ENSG00000239906,Gene Expression,GRCh38,False,ENSG00000239906,NCBITaxon:9606,gene,323,lncRNA

gene_ids,ENSG00000243485,ENSG00000237613,ENSG00000186092,ENSG00000239945,ENSG00000239906
AAACAACGAATAGTTC-1,0.0,0.0,0.0,0.0,0.0
AAACAAGTATCTCCCA-1,0.0,0.0,0.0,0.0,0.0
AAACAATCTACTAGCA-1,0.0,0.0,0.0,0.0,0.0
AAACACCAATAACTGC-1,0.0,0.0,0.0,0.0,0.0
AAACAGAGCGACTCCT-1,0.0,0.0,0.0,0.0,0.0

----------------------------------------------------------------------------------------------------

### Rotem_12W_heart_B1

Source: CellxGene
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_1_cellxgene/07_rotem_12w_heart_b1.h5ad
Origin: https://datasets.cellxgene.cziscience.com/57c7e31e-6bf5-4498-a2d3-2a3728c64ded.h5ad
Size: 36.7MiB
AnnData object with n_obs × n_vars = 4992 × 35476 backed at '/gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_1_cellxgene/07_rotem_12w_heart_b1.h5ad'
    obs: 'in_tissue', 'array_row', 'array_col', 'suspension_type', 'assay_ontology_term_id', 'is_primary_data', 'donor_id', 'sex_ontology_term_id', 'development_stage_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'disease_ontology_term_id', 'tissue_type', 'tissue_ontology_term_id', 'q05cell_abundance_w_sf_Cardiac', 'q05cell_abundance_w_sf_Endothelial', 'q05cell_abundance_w_sf_Immune', 'q05cell_abundance_w_sf_Mesenchymal_clust12', 'q05cell_abundance_w_sf_Mesenchymal_clust15', 'q05cell_abundance_w_sf_Mesenchymal_clust3', 'q05cell_abundance_w_sf_Mesenchymal_clust6', 'q05cell_abundance_w_sf_Mesenchymal_clust9', 'q05cell_abundance_w_sf_Neural', 'annotation', 'cell_type_ontology_term_id', 'cell_type', 'assay', 'disease', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid'
    var: 'feature_types', 'genome', 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type'
    uns: 'citation', 'organism', 'organism_ontology_term_id', 'schema_reference', 'schema_version', 'spatial', 'spatial_metadata', 'title'
    obsm: 'spatial'
n_obs: 4,992; n_vars: 35,476
obs head:

,in_tissue,array_row,array_col,suspension_type,assay_ontology_term_id,is_primary_data,donor_id,sex_ontology_term_id,development_stage_ontology_term_id,self_reported_ethnicity_ontology_term_id,...,annotation,cell_type_ontology_term_id,cell_type,assay,disease,sex,tissue,self_reported_ethnicity,development_stage,observation_joinid
AAACAACGAATAGTTC-1,0,0,16,na,EFO:0022857,True,HsapDv:0000050,PATO:0000383,HsapDv:0000050,unknown,...,NaN,unknown,unknown,Visium Spatial Gene Expression V1,normal,female,outflow tract myocardium,unknown,13th week post-fertilization stage,S{qkR!yc~8
AAACAAGTATCTCCCA-1,1,50,102,na,EFO:0022857,True,HsapDv:0000050,PATO:0000383,HsapDv:0000050,unknown,...,Cardiac,CL:0000746,cardiac muscle cell,Visium Spatial Gene Expression V1,normal,female,outflow tract myocardium,unknown,13th week post-fertilization stage,gFD!+Zqd(i
AAACAATCTACTAGCA-1,0,3,43,na,EFO:0022857,True,HsapDv:0000050,PATO:0000383,HsapDv:0000050,unknown,...,NaN,unknown,unknown,Visium Spatial Gene Expression V1,normal,female,outflow tract myocardium,unknown,13th week post-fertilization stage,OsSlEREYZW
AAACACCAATAACTGC-1,0,59,19,na,EFO:0022857,True,HsapDv:0000050,PATO:0000383,HsapDv:0000050,unknown,...,NaN,unknown,unknown,Visium Spatial Gene Expression V1,normal,female,outflow tract myocardium,unknown,13th week post-fertilization stage,zuU(#yRj2=
AAACAGAGCGACTCCT-1,0,14,94,na,EFO:0022857,True,HsapDv:0000050,PATO:0000383,HsapDv:0000050,unknown,...,NaN,unknown,unknown,Visium Spatial Gene Expression V1,normal,female,outflow tract myocardium,unknown,13th week post-fertilization stage,-$<USDZJGm

var head:

,feature_types,genome,feature_is_filtered,feature_name,feature_reference,feature_biotype,feature_length,feature_type
gene_ids,,,,,,,,
ENSG00000243485,Gene Expression,GRCh38,False,MIR1302-2HG,NCBITaxon:9606,gene,517,lncRNA
ENSG00000237613,Gene Expression,GRCh38,False,FAM138A,NCBITaxon:9606,gene,1015,lncRNA
ENSG00000186092,Gene Expression,GRCh38,False,OR4F5,NCBITaxon:9606,gene,2618,protein_coding
ENSG00000239945,Gene Expression,GRCh38,False,ENSG00000239945,NCBITaxon:9606,gene,1319,lncRNA
ENSG00000239906,Gene Expression,GRCh38,False,ENSG00000239906,NCBITaxon:9606,gene,323,lncRNA

gene_ids,ENSG00000243485,ENSG00000237613,ENSG00000186092,ENSG00000239945,ENSG00000239906
AAACAACGAATAGTTC-1,0.0,0.0,0.0,0.0,0.0
AAACAAGTATCTCCCA-1,0.0,0.0,0.0,0.0,0.0
AAACAATCTACTAGCA-1,0.0,0.0,0.0,0.0,0.0
AAACACCAATAACTGC-1,0.0,0.0,0.0,0.0,0.0
AAACAGAGCGACTCCT-1,0.0,0.0,0.0,0.0,0.0

----------------------------------------------------------------------------------------------------

### Rotem_12W_heart_D1

Source: CellxGene
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_1_cellxgene/08_rotem_12w_heart_d1.h5ad
Origin: https://datasets.cellxgene.cziscience.com/72e35ce5-fb20-46d0-adf9-a8c7f44af287.h5ad
Size: 24.2MiB
AnnData object with n_obs × n_vars = 4992 × 35476 backed at '/gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_1_cellxgene/08_rotem_12w_heart_d1.h5ad'
    obs: 'in_tissue', 'array_row', 'array_col', 'suspension_type', 'assay_ontology_term_id', 'is_primary_data', 'donor_id', 'sex_ontology_term_id', 'development_stage_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'disease_ontology_term_id', 'tissue_type', 'tissue_ontology_term_id', 'q05cell_abundance_w_sf_Cardiac', 'q05cell_abundance_w_sf_Endothelial', 'q05cell_abundance_w_sf_Immune', 'q05cell_abundance_w_sf_Mesenchymal_clust12', 'q05cell_abundance_w_sf_Mesenchymal_clust15', 'q05cell_abundance_w_sf_Mesenchymal_clust3', 'q05cell_abundance_w_sf_Mesenchymal_clust6', 'q05cell_abundance_w_sf_Mesenchymal_clust9', 'q05cell_abundance_w_sf_Neural', 'annotation', 'cell_type_ontology_term_id', 'cell_type', 'assay', 'disease', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid'
    var: 'feature_types', 'genome', 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type'
    uns: 'citation', 'organism', 'organism_ontology_term_id', 'schema_reference', 'schema_version', 'spatial', 'spatial_metadata', 'title'
    obsm: 'spatial'
n_obs: 4,992; n_vars: 35,476
obs head:

,in_tissue,array_row,array_col,suspension_type,assay_ontology_term_id,is_primary_data,donor_id,sex_ontology_term_id,development_stage_ontology_term_id,self_reported_ethnicity_ontology_term_id,...,annotation,cell_type_ontology_term_id,cell_type,assay,disease,sex,tissue,self_reported_ethnicity,development_stage,observation_joinid
AAACAACGAATAGTTC-1,0,0,16,na,EFO:0022857,True,HsapDv:0000050,PATO:0000383,HsapDv:0000050,unknown,...,NaN,unknown,unknown,Visium Spatial Gene Expression V1,normal,female,outflow tract myocardium,unknown,13th week post-fertilization stage,S{qkR!yc~8
AAACAAGTATCTCCCA-1,1,50,102,na,EFO:0022857,True,HsapDv:0000050,PATO:0000383,HsapDv:0000050,unknown,...,Cardiac,CL:0000746,cardiac muscle cell,Visium Spatial Gene Expression V1,normal,female,outflow tract myocardium,unknown,13th week post-fertilization stage,gFD!+Zqd(i
AAACAATCTACTAGCA-1,0,3,43,na,EFO:0022857,True,HsapDv:0000050,PATO:0000383,HsapDv:0000050,unknown,...,NaN,unknown,unknown,Visium Spatial Gene Expression V1,normal,female,outflow tract myocardium,unknown,13th week post-fertilization stage,OsSlEREYZW
AAACACCAATAACTGC-1,0,59,19,na,EFO:0022857,True,HsapDv:0000050,PATO:0000383,HsapDv:0000050,unknown,...,NaN,unknown,unknown,Visium Spatial Gene Expression V1,normal,female,outflow tract myocardium,unknown,13th week post-fertilization stage,zuU(#yRj2=
AAACAGAGCGACTCCT-1,0,14,94,na,EFO:0022857,True,HsapDv:0000050,PATO:0000383,HsapDv:0000050,unknown,...,NaN,unknown,unknown,Visium Spatial Gene Expression V1,normal,female,outflow tract myocardium,unknown,13th week post-fertilization stage,-$<USDZJGm

var head:

,feature_types,genome,feature_is_filtered,feature_name,feature_reference,feature_biotype,feature_length,feature_type
gene_ids,,,,,,,,
ENSG00000243485,Gene Expression,GRCh38,False,MIR1302-2HG,NCBITaxon:9606,gene,517,lncRNA
ENSG00000237613,Gene Expression,GRCh38,False,FAM138A,NCBITaxon:9606,gene,1015,lncRNA
ENSG00000186092,Gene Expression,GRCh38,False,OR4F5,NCBITaxon:9606,gene,2618,protein_coding
ENSG00000239945,Gene Expression,GRCh38,False,ENSG00000239945,NCBITaxon:9606,gene,1319,lncRNA
ENSG00000239906,Gene Expression,GRCh38,False,ENSG00000239906,NCBITaxon:9606,gene,323,lncRNA

gene_ids,ENSG00000243485,ENSG00000237613,ENSG00000186092,ENSG00000239945,ENSG00000239906
AAACAACGAATAGTTC-1,0.0,0.0,0.0,0.0,0.0
AAACAAGTATCTCCCA-1,0.0,0.0,0.0,0.0,0.0
AAACAATCTACTAGCA-1,0.0,0.0,0.0,0.0,0.0
AAACACCAATAACTGC-1,0.0,0.0,0.0,0.0,0.0
AAACAGAGCGACTCCT-1,0.0,0.0,0.0,0.0,0.0

----------------------------------------------------------------------------------------------------

### Rotem_12W_heart_A1

Source: CellxGene
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_1_cellxgene/09_rotem_12w_heart_a1.h5ad
Origin: https://datasets.cellxgene.cziscience.com/731fb49f-4a81-48d5-9f28-ee1b08f1018d.h5ad
Size: 42.8MiB
AnnData object with n_obs × n_vars = 4992 × 35476 backed at '/gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_1_cellxgene/09_rotem_12w_heart_a1.h5ad'
    obs: 'in_tissue', 'array_row', 'array_col', 'suspension_type', 'assay_ontology_term_id', 'is_primary_data', 'donor_id', 'sex_ontology_term_id', 'development_stage_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'disease_ontology_term_id', 'tissue_type', 'tissue_ontology_term_id', 'q05cell_abundance_w_sf_Cardiac', 'q05cell_abundance_w_sf_Endothelial', 'q05cell_abundance_w_sf_Immune', 'q05cell_abundance_w_sf_Mesenchymal_clust12', 'q05cell_abundance_w_sf_Mesenchymal_clust15', 'q05cell_abundance_w_sf_Mesenchymal_clust3', 'q05cell_abundance_w_sf_Mesenchymal_clust6', 'q05cell_abundance_w_sf_Mesenchymal_clust9', 'q05cell_abundance_w_sf_Neural', 'annotation', 'cell_type_ontology_term_id', 'cell_type', 'assay', 'disease', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid'
    var: 'feature_types', 'genome', 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type'
    uns: 'citation', 'organism', 'organism_ontology_term_id', 'schema_reference', 'schema_version', 'spatial', 'spatial_metadata', 'title'
    obsm: 'spatial'
n_obs: 4,992; n_vars: 35,476
obs head:

,in_tissue,array_row,array_col,suspension_type,assay_ontology_term_id,is_primary_data,donor_id,sex_ontology_term_id,development_stage_ontology_term_id,self_reported_ethnicity_ontology_term_id,...,annotation,cell_type_ontology_term_id,cell_type,assay,disease,sex,tissue,self_reported_ethnicity,development_stage,observation_joinid
AAACAACGAATAGTTC-1,0,0,16,na,EFO:0022857,True,HsapDv:0000050,PATO:0000383,HsapDv:0000050,unknown,...,NaN,unknown,unknown,Visium Spatial Gene Expression V1,normal,female,outflow tract myocardium,unknown,13th week post-fertilization stage,S{qkR!yc~8
AAACAAGTATCTCCCA-1,1,50,102,na,EFO:0022857,True,HsapDv:0000050,PATO:0000383,HsapDv:0000050,unknown,...,Cardiac,CL:0000746,cardiac muscle cell,Visium Spatial Gene Expression V1,normal,female,outflow tract myocardium,unknown,13th week post-fertilization stage,gFD!+Zqd(i
AAACAATCTACTAGCA-1,0,3,43,na,EFO:0022857,True,HsapDv:0000050,PATO:0000383,HsapDv:0000050,unknown,...,NaN,unknown,unknown,Visium Spatial Gene Expression V1,normal,female,outflow tract myocardium,unknown,13th week post-fertilization stage,OsSlEREYZW
AAACACCAATAACTGC-1,0,59,19,na,EFO:0022857,True,HsapDv:0000050,PATO:0000383,HsapDv:0000050,unknown,...,NaN,unknown,unknown,Visium Spatial Gene Expression V1,normal,female,outflow tract myocardium,unknown,13th week post-fertilization stage,zuU(#yRj2=
AAACAGAGCGACTCCT-1,1,14,94,na,EFO:0022857,True,HsapDv:0000050,PATO:0000383,HsapDv:0000050,unknown,...,Cardiac,CL:0000746,cardiac muscle cell,Visium Spatial Gene Expression V1,normal,female,outflow tract myocardium,unknown,13th week post-fertilization stage,-$<USDZJGm

var head:

,feature_types,genome,feature_is_filtered,feature_name,feature_reference,feature_biotype,feature_length,feature_type
gene_ids,,,,,,,,
ENSG00000243485,Gene Expression,GRCh38,False,MIR1302-2HG,NCBITaxon:9606,gene,517,lncRNA
ENSG00000237613,Gene Expression,GRCh38,False,FAM138A,NCBITaxon:9606,gene,1015,lncRNA
ENSG00000186092,Gene Expression,GRCh38,False,OR4F5,NCBITaxon:9606,gene,2618,protein_coding
ENSG00000239945,Gene Expression,GRCh38,False,ENSG00000239945,NCBITaxon:9606,gene,1319,lncRNA
ENSG00000239906,Gene Expression,GRCh38,False,ENSG00000239906,NCBITaxon:9606,gene,323,lncRNA

gene_ids,ENSG00000243485,ENSG00000237613,ENSG00000186092,ENSG00000239945,ENSG00000239906
AAACAACGAATAGTTC-1,0.0,0.0,0.0,0.0,0.0
AAACAAGTATCTCCCA-1,0.0,0.0,0.0,0.0,0.0
AAACAATCTACTAGCA-1,0.0,0.0,0.0,0.0,0.0
AAACACCAATAACTGC-1,0.0,0.0,0.0,0.0,0.0
AAACAGAGCGACTCCT-1,0.0,0.0,0.0,0.0,0.0

----------------------------------------------------------------------------------------------------

### Single-nuclei RNA-seq of human outflow tract and aortic valve tissue

Source: CellxGene
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_1_cellxgene/10_single_nuclei_rna_seq_human_outflow_tract_aortic_valve.h5ad
Origin: https://datasets.cellxgene.cziscience.com/e6c07fbd-c90b-48c0-b6e3-b03b2d7218c5.h5ad
Size: 437.1MiB
AnnData object with n_obs × n_vars = 30125 × 31008 backed at '/gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_1_cellxgene/10_single_nuclei_rna_seq_human_outflow_tract_aortic_valve.h5ad'
    obs: 'cellType_global', 'louvain_0.1', 'louvain_0.4', 'Sample', 'cell_type_ontology_term_id', 'development_stage_ontology_term_id', 'sex_ontology_term_id', 'tissue_ontology_term_id', 'assay_ontology_term_id', 'donor_id', 'self_reported_ethnicity_ontology_term_id', 'disease_ontology_term_id', 'tissue_type', 'suspension_type', 'batch', 'is_primary_data', 'cell_type', 'assay', 'disease', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid'
    var: 'mt', 'ribo', 'hb', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean-0', 'detected-0', 'n_cells_by_counts-0', 'pct_dropout-0', 'PercentClust1-0', 'PercentClust2-0', 'PercentClust3-0', 'PercentClust4-0', 'PercentClust5-0', 'PercentClust6-0', 'PercentClust7-0', 'PercentClust8-0', 'PercentClust9-0', 'PercentClust10-0', 'PercentClust11-0', 'PercentClust12-0', 'PercentClust13-0', 'PercentClust14-0', 'PercentSample12W_rep1-0', 'PercentSample12W_rep2-0', 'PercentSample8W_rep1-0', 'PercentSample8W_rep2-0', 'PercentTotal-0', 'Symbol-1', 'Type-1', 'SEQNAME-1', 'is_mito-1', 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type'
    uns: 'citation', 'organism', 'organism_ontology_term_id', 'schema_reference', 'schema_version', 'title'
    obsm: 'X_pca', 'X_tsne', 'X_umap', 'tsne', 'umap'
n_obs: 30,125; n_vars: 31,008
obs head:

,cellType_global,louvain_0.1,louvain_0.4,Sample,cell_type_ontology_term_id,development_stage_ontology_term_id,sex_ontology_term_id,tissue_ontology_term_id,assay_ontology_term_id,donor_id,...,batch,is_primary_data,cell_type,assay,disease,sex,tissue,self_reported_ethnicity,development_stage,observation_joinid
AAACCCAAGAGTTGAT-1-0,Mesenchymal,4,4,CS16-17_1,CL:0000569,HsapDv:0000024,PATO:0000384,UBERON:0004265,EFO:0009922,pooled_CS16-17_1,...,0,True,cardiac mesenchymal cell,10x 3' v3,normal,male,outflow tract myocardium,unknown,Carnegie stage 17,f%5_I8?*E4
AAACCCACAGGACGAT-1-0,Mesenchymal,4,20,CS16-17_1,CL:0000569,HsapDv:0000024,PATO:0000384,UBERON:0004265,EFO:0009922,pooled_CS16-17_1,...,0,True,cardiac mesenchymal cell,10x 3' v3,normal,male,outflow tract myocardium,unknown,Carnegie stage 17,r>2p7Tk~Ua
AAACCCACATGTACGT-1-0,Cardiac,2,2,CS16-17_1,CL:0000746,HsapDv:0000024,PATO:0000384,UBERON:0004265,EFO:0009922,pooled_CS16-17_1,...,0,True,cardiac muscle cell,10x 3' v3,normal,male,outflow tract myocardium,unknown,Carnegie stage 17,fX#y9)XMQd
AAACCCAGTTGATCGT-1-0,Mesenchymal,4,4,CS16-17_1,CL:0000569,HsapDv:0000024,PATO:0000384,UBERON:0004265,EFO:0009922,pooled_CS16-17_1,...,0,True,cardiac mesenchymal cell,10x 3' v3,normal,male,outflow tract myocardium,unknown,Carnegie stage 17,VabAi?xh^h
AAACGAAAGCACTAAA-1-0,Cardiac,2,17,CS16-17_1,CL:0000746,HsapDv:0000024,PATO:0000384,UBERON:0004265,EFO:0009922,pooled_CS16-17_1,...,0,True,cardiac muscle cell,10x 3' v3,normal,male,outflow tract myocardium,unknown,Carnegie stage 17,n?JvqHQbOH

var head:

,mt,ribo,hb,n_cells_by_counts,mean_counts,pct_dropout_by_counts,total_counts,highly_variable,means,dispersions,...,Symbol-1,Type-1,SEQNAME-1,is_mito-1,feature_is_filtered,feature_name,feature_reference,feature_biotype,feature_length,feature_type
ENSG00000243485,True,True,True,NaN,NaN,NaN,NaN,True,NaN,NaN,...,NaN,NaN,NaN,NaN,True,MIR1302-2HG,NCBITaxon:9606,gene,517,lncRNA
ENSG00000237613,True,True,True,NaN,NaN,NaN,NaN,True,NaN,NaN,...,NaN,NaN,NaN,NaN,True,FAM138A,NCBITaxon:9606,gene,1015,lncRNA
ENSG00000186092,True,True,True,NaN,NaN,NaN,NaN,True,NaN,NaN,...,NaN,NaN,NaN,NaN,True,OR4F5,NCBITaxon:9606,gene,2618,protein_coding
ENSG00000239945,True,True,True,NaN,NaN,NaN,NaN,True,NaN,NaN,...,NaN,NaN,NaN,NaN,True,ENSG00000239945,NCBITaxon:9606,gene,1319,lncRNA
ENSG00000239906,True,True,True,NaN,NaN,NaN,NaN,True,NaN,NaN,...,NaN,NaN,NaN,NaN,True,ENSG00000239906,NCBITaxon:9606,gene,323,lncRNA

,ENSG00000243485,ENSG00000237613,ENSG00000186092,ENSG00000239945,ENSG00000239906
AAACCCAAGAGTTGAT-1-0,0.0,0.0,0.0,0.0,0.0
AAACCCACAGGACGAT-1-0,0.0,0.0,0.0,0.0,0.0
AAACCCACATGTACGT-1-0,0.0,0.0,0.0,0.0,0.0
AAACCCAGTTGATCGT-1-0,0.0,0.0,0.0,0.0,0.0
AAACGAAAGCACTAAA-1-0,0.0,0.0,0.0,0.0,0.0

----------------------------------------------------------------------------------------------------

### GSE157329 raw counts

Source: Human Early Embryogenesis Atlas
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_2_human_early_embryogenesis_atlas/93a9e248-b704-419f-b5ab-a0b96eefeaa0/GSE157329_raw_counts.mtx.gz
Origin: HCA/Azul manifest URL from documents/data_sources.txt
Size: 1.3GiB
Matrix Market header: %%MatrixMarket matrix coordinate integer general
Matrix dimensions line: 32351 185140 430775975

  row column value
0  38      1     1
1  42      1     1
2  52      1     2
3  54      1     1
4  69      1     1

----------------------------------------------------------------------------------------------------

### Human cardiogenesis in vitro expression matrix

Source: UCSC Cells
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_3_ucsc_cells/01_human_cardiogenesis_in_vitro_exprMatrix.tsv.gz
Origin: Local copy corresponding to https://cells.ucsc.edu/cardiogenesis-atac/in-vitro/exprMatrix.tsv.gz
Size: 1.7GiB

,0,1,2,3,4,5,6,7,8
0,,CF_v2#TCACCACAGGATCCTT-1,CF_v2#ATAGGCTCAAAGGTCG-1,CF_v2#GTGACATAGAGGCAGG-1,CF_v2#TGTGTCCTCGTGGCGT-1,CF_v2#AGATTCGGTGGCGCTT-1,CF_v2#ACAAAGAGTTTCCGGG-1,CF_v2#GCGAGAAGTACGTAGG-1,... 78601 more columns
1,OR4F5,0,0,0,0,0,0,0,... 78601 more columns
2,LOC729737,0,0,0,0,0,0,0,... 78601 more columns
3,LOC101928626,0,0,0,0,0,0,0,... 78601 more columns
4,FAM87B,0,0,0,0,0.332,0,0,... 78601 more columns

----------------------------------------------------------------------------------------------------

### Human cardiogenesis in vivo expression matrix

Source: UCSC Cells
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_3_ucsc_cells/02_human_cardiogenesis_in_vivo_exprMatrix.tsv.gz
Origin: Local copy corresponding to https://cells.ucsc.edu/cardiogenesis-atac/in-vivo/exprMatrix.tsv.gz
Size: 340.3MiB

,0,1,2,3,4,5,6,7,8
0,gene,F19_v2#GGATGAGCAACGTCCG-1,F19_v2#TTCTAACTCCGTCAAA-1,F19_v2#CACTGAATCTTATCAC-1,F19_v2#GTGATCATCCCAGTAA-1,F19_v2#AAACGAAAGACTAATG-1,F19_v2#GACTAACTCCTTCGAC-1,F19_v2#TACATTCAGGTCGTTT-1,... 30419 more columns
1,OR4F5,0,0,0,0,0,0,0,... 30419 more columns
2,LOC729737,0,0,0,0,0,0,0,... 30419 more columns
3,LOC101928626,0,0,0,0,0,0,0,... 30419 more columns
4,FAM87B,0,0,0,0,0,0,1.024,... 30419 more columns

----------------------------------------------------------------------------------------------------

### Multiomic human heart snRNA-seq matrix

Source: UCSC Cells
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_3_ucsc_cells/03_multiomic_human_heart_snrna_seq_matrix.mtx.gz
Origin: Local copy corresponding to https://cells.ucsc.edu/multiomic-human-heart/rna/matrix.mtx.gz
Size: 20.5GiB
Matrix Market header: %%MatrixMarket matrix coordinate real general
Comments:
  %
Matrix dimensions line: 16115 2275105 3167264648

  row column         value
0   1   7441  1.580822e+00
1   1  12600  9.272307e-01
2   1  14307  1.466197e+00
3   1  15355  8.397833e-01
4   1  16002  7.379873e-01

----------------------------------------------------------------------------------------------------

### Multiomic human heart snATAC-seq matrix

Source: UCSC Cells
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_3_ucsc_cells/04_multiomic_human_heart_snatac_seq_matrix.mtx.gz
Origin: Local copy corresponding to https://cells.ucsc.edu/multiomic-human-heart/atac/matrix.mtx.gz
Size: 24.7GiB
Matrix Market header: %%MatrixMarket matrix coordinate real general
Comments:
  %
Matrix dimensions line: 654221 690044 3151786687

  row  column         value
0   1  503463  5.385755e-01
1   1  591699  7.028933e-01
2   1  543397  2.408080e-01
3   1  223370  1.657028e-01
4   1  541157  3.061948e-01

----------------------------------------------------------------------------------------------------

### Heart of Cells overall heart scRNA-seq expression matrix

Source: UCSC Cells
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_3_ucsc_cells/05_heart_of_cells_overall_heart_scrna_seq_exprMatrix.tsv.gz
Origin: Local copy corresponding to UCSC Heart of Cells overall heart exprMatrix.tsv.gz
Size: 360.6MiB

,0,1,2,3,4,5,6,7,8
0,gene,13W3D_LA_AAACCTGCAAACTGTC,13W3D_LA_AAACCTGCAAGGGTCA,13W3D_LA_AAACCTGCAAGTAATG,13W3D_LA_AAACCTGCACATAACC,13W3D_LA_AAACCTGCAGACGCCT,13W3D_LA_AAACCTGCATACGCTA,13W3D_LA_AAACCTGGTCCGAAGA,... 142939 more columns
1,MIR1302-2HG|MIR1302-2HG,0,0,0,0,0,0,0,... 142939 more columns
2,FAM138A|FAM138A,0,0,0,0,0,0,0,... 142939 more columns
3,OR4F5|OR4F5,0,0,0,0,0,0,0,... 142939 more columns
4,AL627309.1|AL627309.1,0,0,0,0,0,0,0,... 142939 more columns

----------------------------------------------------------------------------------------------------

### Human fetal cis-regulatory elements

Source: Lab Directory
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_4_lab_directory/01_human_fetal_cis_regulatory_elements.loom
Origin: /gladstone/theodoris/lab/genecorpus_XM/corpus_loom_files/genecorpus_95M_loom/9010519993/File_S3_Matrix.Gene_Raw_Counts_of_Cells.loom
Size: 1.2GiB
HDF5 top-level keys: ['attrs', 'col_attrs', 'col_graphs', 'layers', 'matrix', 'row_attrs', 'row_graphs']
matrix shape: (19329, 185061); dtype: float64

     0    1    2    3    4
0  0.0  0.0  0.0  0.0  0.0
1  1.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  1.0

row_attrs keys: ['ensembl_id', 'ensembl_id_version', 'ensembl_original', 'gene_name', 'gene_original', 'gene_type']
col_attrs keys: ['cell_id', 'dataset', 'filter_pass', 'n_counts', 'n_func_genes', 'organ_specific', 'pct_mito', 'platform', 'sample', 'study', 'unique_cell_id']

----------------------------------------------------------------------------------------------------

### Human fetal striatum atlas

Source: Lab Directory
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_4_lab_directory/02_human_fetal_striatum_atlas.loom
Origin: /gladstone/theodoris/lab/genecorpus_XM/corpus_loom_files/genecorpus_95M_loom/E-MTAB-8894/E-MTAB-8894.loom
Size: 1.4GiB
HDF5 top-level keys: ['attrs', 'col_attrs', 'col_graphs', 'layers', 'matrix', 'row_attrs', 'row_graphs']
matrix shape: (38263, 150129); dtype: float64

     0    1    2    3    4
0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0

row_attrs keys: ['ensembl_id', 'ensembl_id_version', 'ensembl_original', 'gene_name', 'gene_type']
col_attrs keys: ['cell_id', 'dataset', 'filter_pass', 'n_counts', 'n_func_genes', 'organ_specific', 'pct_mito', 'platform', 'sample', 'study', 'unique_cell_id']

----------------------------------------------------------------------------------------------------

### Human megakaryocyte development: yolk-sac stage

Source: Lab Directory
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_4_lab_directory/03_human_megakaryocyte_development/GSE144024_YS_Stage_gene.loom
Origin: /gladstone/theodoris/lab/genecorpus_XM/corpus_loom_files/genecorpus_95M_loom/4110056855/
Size: 90.9MiB
HDF5 top-level keys: ['attrs', 'col_attrs', 'col_graphs', 'layers', 'matrix', 'row_attrs', 'row_graphs']
matrix shape: (17614, 11021); dtype: int64

   0  1  2  3  4
0  0  0  0  0  0
1  0  0  0  0  0
2  0  0  0  0  0
3  0  0  2  2  0
4  0  0  0  0  0

row_attrs keys: ['ensembl_id', 'ensembl_id_version', 'ensembl_original', 'gene_name', 'gene_original', 'gene_type']
col_attrs keys: ['cell_id', 'dataset', 'filter_pass', 'n_counts', 'n_func_genes', 'organ_specific', 'pct_mito', 'platform', 'sample', 'study', 'unique_cell_id']

----------------------------------------------------------------------------------------------------

### Human megakaryocyte development: hESC Day 0

Source: Lab Directory
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_4_lab_directory/03_human_megakaryocyte_development/GSE144024_hESC_Day0_gene.loom
Origin: /gladstone/theodoris/lab/genecorpus_XM/corpus_loom_files/genecorpus_95M_loom/4110056855/
Size: 76.2MiB
HDF5 top-level keys: ['attrs', 'col_attrs', 'col_graphs', 'layers', 'matrix', 'row_attrs', 'row_graphs']
matrix shape: (17091, 9485); dtype: int64

   0  1  2  3  4
0  0  0  0  0  0
1  0  0  1  0  0
2  0  0  0  0  0
3  0  0  0  0  1
4  0  0  0  0  0

row_attrs keys: ['ensembl_id', 'ensembl_id_version', 'ensembl_original', 'gene_name', 'gene_original', 'gene_type']
col_attrs keys: ['cell_id', 'dataset', 'filter_pass', 'n_counts', 'n_func_genes', 'organ_specific', 'pct_mito', 'platform', 'sample', 'study', 'unique_cell_id']

----------------------------------------------------------------------------------------------------

### Fetal vs. adult human epicardium

Source: Lab Directory
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_4_lab_directory/04_fetal_vs_adult_human_epicardium.loom
Origin: /gladstone/theodoris/lab/genecorpus_XM/corpus_loom_files/genecorpus_95M_loom/cxg/5500c673-1610-40a0-86d9-64d987ae50e6.loom
Size: 302.0MiB
HDF5 top-level keys: ['attrs', 'col_attrs', 'col_graphs', 'layers', 'matrix', 'row_attrs', 'row_graphs']
matrix shape: (60664, 30889); dtype: float32

     0    1    2    3    4
0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0

row_attrs keys: ['ensembl_id', 'ensembl_id_version', 'ensembl_original', 'gene_name', 'gene_type']
col_attrs keys: ['cell_subclass', 'cell_type', 'dataset', 'development_stage', 'disease', 'donor_id', 'filter_pass', 'n_counts', 'n_func_genes', 'organ_specific', 'pct_mito', 'platform', 'sample', 'self_reported_ethnicity', 'sex', 'study', 'tissue', 'tissue_general', 'unique_cell_id']

----------------------------------------------------------------------------------------------------

## Optional: Inspect One Source at a Time

Use this section when you want smaller output chunks.

In [5]:
available_sources = sorted({ds["source"] for ds in DATASETS})
available_sources

['CellxGene', 'Human Early Embryogenesis Atlas', 'Lab Directory', 'UCSC Cells']

In [9]:
SOURCE_TO_RUN = "Lab Directory"  # Change to one of available_sources.

for ds in DATASETS:
    if ds["source"] == SOURCE_TO_RUN:
        inspect_dataset(ds)
        print("\n" + "-" * 100 + "\n")

### Human fetal cis-regulatory elements

Source: Lab Directory
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_4_lab_directory/01_human_fetal_cis_regulatory_elements.loom
Origin: /gladstone/theodoris/lab/genecorpus_XM/corpus_loom_files/genecorpus_95M_loom/9010519993/File_S3_Matrix.Gene_Raw_Counts_of_Cells.loom
Size: 1.2GiB
HDF5 top-level keys: ['attrs', 'col_attrs', 'col_graphs', 'layers', 'matrix', 'row_attrs', 'row_graphs']
matrix shape: (19329, 185061); dtype: float64

     0    1    2    3    4
0  0.0  0.0  0.0  0.0  0.0
1  1.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  1.0

row_attrs keys: ['ensembl_id', 'ensembl_id_version', 'ensembl_original', 'gene_name', 'gene_original', 'gene_type']
col_attrs keys: ['cell_id', 'dataset', 'filter_pass', 'n_counts', 'n_func_genes', 'organ_specific', 'pct_mito', 'platform', 'sample', 'study', 'unique_cell_id']

----------------------------------------------------------------------------------------------------

### Human fetal striatum atlas

Source: Lab Directory
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_4_lab_directory/02_human_fetal_striatum_atlas.loom
Origin: /gladstone/theodoris/lab/genecorpus_XM/corpus_loom_files/genecorpus_95M_loom/E-MTAB-8894/E-MTAB-8894.loom
Size: 1.4GiB
HDF5 top-level keys: ['attrs', 'col_attrs', 'col_graphs', 'layers', 'matrix', 'row_attrs', 'row_graphs']
matrix shape: (38263, 150129); dtype: float64

     0    1    2    3    4
0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0

row_attrs keys: ['ensembl_id', 'ensembl_id_version', 'ensembl_original', 'gene_name', 'gene_type']
col_attrs keys: ['cell_id', 'dataset', 'filter_pass', 'n_counts', 'n_func_genes', 'organ_specific', 'pct_mito', 'platform', 'sample', 'study', 'unique_cell_id']

----------------------------------------------------------------------------------------------------

### Human megakaryocyte development: yolk-sac stage

Source: Lab Directory
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_4_lab_directory/03_human_megakaryocyte_development/GSE144024_YS_Stage_gene.loom
Origin: /gladstone/theodoris/lab/genecorpus_XM/corpus_loom_files/genecorpus_95M_loom/4110056855/
Size: 90.9MiB
HDF5 top-level keys: ['attrs', 'col_attrs', 'col_graphs', 'layers', 'matrix', 'row_attrs', 'row_graphs']
matrix shape: (17614, 11021); dtype: int64

   0  1  2  3  4
0  0  0  0  0  0
1  0  0  0  0  0
2  0  0  0  0  0
3  0  0  2  2  0
4  0  0  0  0  0

row_attrs keys: ['ensembl_id', 'ensembl_id_version', 'ensembl_original', 'gene_name', 'gene_original', 'gene_type']
col_attrs keys: ['cell_id', 'dataset', 'filter_pass', 'n_counts', 'n_func_genes', 'organ_specific', 'pct_mito', 'platform', 'sample', 'study', 'unique_cell_id']

----------------------------------------------------------------------------------------------------

### Human megakaryocyte development: hESC Day 0

Source: Lab Directory
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_4_lab_directory/03_human_megakaryocyte_development/GSE144024_hESC_Day0_gene.loom
Origin: /gladstone/theodoris/lab/genecorpus_XM/corpus_loom_files/genecorpus_95M_loom/4110056855/
Size: 76.2MiB
HDF5 top-level keys: ['attrs', 'col_attrs', 'col_graphs', 'layers', 'matrix', 'row_attrs', 'row_graphs']
matrix shape: (17091, 9485); dtype: int64

   0  1  2  3  4
0  0  0  0  0  0
1  0  0  1  0  0
2  0  0  0  0  0
3  0  0  0  0  1
4  0  0  0  0  0

row_attrs keys: ['ensembl_id', 'ensembl_id_version', 'ensembl_original', 'gene_name', 'gene_original', 'gene_type']
col_attrs keys: ['cell_id', 'dataset', 'filter_pass', 'n_counts', 'n_func_genes', 'organ_specific', 'pct_mito', 'platform', 'sample', 'study', 'unique_cell_id']

----------------------------------------------------------------------------------------------------

### Fetal vs. adult human epicardium

Source: Lab Directory
Path: /gladstone/theodoris/lab/enockniyonkuru/maxtoki_development_data/source_4_lab_directory/04_fetal_vs_adult_human_epicardium.loom
Origin: /gladstone/theodoris/lab/genecorpus_XM/corpus_loom_files/genecorpus_95M_loom/cxg/5500c673-1610-40a0-86d9-64d987ae50e6.loom
Size: 302.0MiB
HDF5 top-level keys: ['attrs', 'col_attrs', 'col_graphs', 'layers', 'matrix', 'row_attrs', 'row_graphs']
matrix shape: (60664, 30889); dtype: float32

     0    1    2    3    4
0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0

row_attrs keys: ['ensembl_id', 'ensembl_id_version', 'ensembl_original', 'gene_name', 'gene_type']
col_attrs keys: ['cell_subclass', 'cell_type', 'dataset', 'development_stage', 'disease', 'donor_id', 'filter_pass', 'n_counts', 'n_func_genes', 'organ_specific', 'pct_mito', 'platform', 'sample', 'self_reported_ethnicity', 'sex', 'study', 'tissue', 'tissue_general', 'unique_cell_id']

----------------------------------------------------------------------------------------------------

## Optional: Supporting Files

These files are not primary datasets, but they are useful QC/log artifacts copied with the megakaryocyte development loom files.

In [ ]:
for path in SUPPORTING_FILES:
    display(Markdown(f"### {path.name}"))
    print(f"Path: {path}")
    if not path.exists():
        print("MISSING")
        continue
    print(f"Size: {format_bytes(path.stat().st_size)}")
    suffixes = "".join(path.suffixes).lower()
    if suffixes.endswith(".txt"):
        preview_text(path)
    elif suffixes.endswith(".pickle"):
        preview_pickle(path)
    print("\n" + "-" * 100 + "\n")